version: "3.9"
services:
  app:
    build: ../apps/poc-app/log4j-exploit
    container_name: app
    restart: unless-stopped
    labels:
        traefik.enable: true
        traefik.http.routers.app.rule: "Host(`${TRAEFIK_DOMAIN}.${BASE_DOMAIN}`) && PathPrefix(`/app`)"
        traefik.http.routers.app.entrypoints: "https"
        traefik.http.routers.app.tls: true
        traefik.http.routers.app.service: "app"
        traefik.http.services.app.loadbalancer.server.port: 8080

